"""Reporting: tables and plots for DSGE model results."""

from dsgekit.report.plots import (
    close_figures,
    plot_autocorrelation,
    plot_eigenvalues,
    plot_fevd,
    plot_fevd_all,
    plot_irf,
    plot_irf_comparison,
    plot_irf_single_variable,
    plot_simulation,
    plot_simulation_distribution,
    save_figure,
    show_figures,
)
from dsgekit.report.tables import (
    TableFormat,
    TableFormatter,
    autocorrelation_table,
    blanchard_kahn_summary,
    correlation_table,
    eigenvalues_table,
    fevd_table,
    format_model_summary,
    format_moments,
    format_parameters,
    format_steady_state,
    irf_comparison_table,
    irf_table,
    model_summary,
    moments_table,
    parameters_table,
    shocks_table,
    steady_state_table,
)

__all__ = [
    # Tables
    "TableFormat",
    "TableFormatter",
    "parameters_table",
    "steady_state_table",
    "shocks_table",
    "moments_table",
    "correlation_table",
    "autocorrelation_table",
    "irf_table",
    "irf_comparison_table",
    "fevd_table",
    "eigenvalues_table",
    "model_summary",
    "blanchard_kahn_summary",
    "format_parameters",
    "format_steady_state",
    "format_moments",
    "format_model_summary",
    # Plots
    "plot_irf",
    "plot_irf_comparison",
    "plot_irf_single_variable",
    "plot_fevd",
    "plot_fevd_all",
    "plot_simulation",
    "plot_simulation_distribution",
    "plot_autocorrelation",
    "plot_eigenvalues",
    "save_figure",
    "show_figures",
    "close_figures",
]
